### ISSUE TITLE
there are two registeration activities and the register.java is springing with errors

### ISSUE THREAD

**Issue by k1ycee** [hngi/android-kidstories#65]

**Comment by vague369** [comment]
Has this issue not been addressed?

**Comment by codose** [comment]
Yes

**Comment by k1ycee** [comment]
It's kinda not my problem thanks to
@Ritaroid you guys have fun with HNG I'm no longer there with you guys.

**Comment by vague369** [comment]
Why? What happened?

**Comment by Rita-Okonkwo** [comment]
Excuse me Sir @k1ycee , thanks to me that what? What did I do to you?

**Comment by k1ycee** [comment]
I'm not on HNG again that's what happened
It's up to you guys to do your best and finish at stage 10

**Comment by Rita-Okonkwo** [comment]
So please why are you thanking me for this, I want to understand

**Comment by k1ycee** [comment]
You were the one that assigned tasks right I never got assigned any task.
Even though I worked on a page and added a feature it didn't mean shit cos
I wasn't assigned a task on the pivotal tracker

**Comment by Rita-Okonkwo** [comment]
Excuse me? Firstly I wasn't the only one assigning tasks. Secondly, if you really worked on a page why didn't you ask for it to be added on the PT? You people amaze me

**Comment by k1ycee** [comment]
Wow ask @Loveotudor if she asked @Denzel if he did anything
I don't know if it was added but if there's any tune in that app it's
thanks to me
The edit profile page was also what I worked on

**Comment by k1ycee** [comment]
What I was told was that since I wasn't assigned a task on the PT whatever
I had done didn't mean shit

**Comment by Rita-Okonkwo** [comment]
So why am I getting blamed here when Love, who was the team lead was aware of your task and didn't add it on the PT? Please mind your words and stop making me look bad for no good reason

**Comment by Rita-Okonkwo** [comment]
The mentors needed the PT link as proof that you actually worked. You'd have told love to update your task on PT

**Comment by k1ycee** [comment]
You were assigning tasks when I requested for a task you were the one
attending to people and I asked continuously 4 good times after you
reassigned the Google auth API to the other guy but ma no you didn't do
anything about it.
I am complaining of you not responding when you could've I'm not painting
you black.
I'm saying you could have done better.
I'm out of HNG and believe me it's a good thing on my end.
I got another stuff same day I was kicked out.

**Comment by k1ycee** [comment]
Oh both of us were chatting before I got kicked out.

**Comment by Rita-Okonkwo** [comment]
You are painting me black. Infact what you're trying to say is that I'm responsible for your eviction from hng. I was just a deputy lead. There were PMs, there was a lead, there was another deputy lead. If I didn't respond to you, what happened to the others? Also you claimed you added features and love was aware, why didn't you tell her to include your task on PT. Stop looking for who to blame for what's obviously your fault. Sorry about your eviction and success in your future endeavors

**Comment by k1ycee** [comment]
Guys @RitaRoid is not to be blamed
Please I wasn't insinuating that and please it was not my fault obviously
someone deleted my PT maybe you didn't know that but well it's pointless
talking about this y'all are on GitHub to do something right now right

**Comment by k1ycee** [comment]
All team leads are to blamed deputy or not. You guys should learn to
organize yourselves 😉

**Comment by joshbillionz** [comment]
we chat here too? lol

**Comment by k1ycee** [comment]
cool
